databases:
 - name: Starter DB
   databaseName: starter
   user: starter

services:
 - type: web
   name: Starter API
   env: python
   dockerfilePath: ./backend/Dockerfile
   dockerContext: ./backend
   dockerCommand: ./entrypoint.sh
   envVars:
     - key: DB_HOST
       fromDatabase:
         name: starter
         property: host
     - key: DB_HOST_PORT
       fromDatabase:
         name: starter
         property: port
     - key: DB_NAME
       fromDatabase:
         name: starter
         property: name
     - key: DB_PASSWORD
       fromDatabase:
         name: starter
         property: password
     - key: DB_USER
       fromDatabase:
         name: starter
         property: user
     - key: SECRET_KEY
       generateValue: true

  - type: web
    name: Starter Frontend
    env: static
    buildCommand: cd frontend && npm install && npm run-script build
    staticPublishPath: ./frontend/build
